"""
ROBOT 2 — RYAN (Turbo) — OUTTAKES
Run this on Robot 2. Each scene is self-contained — you can re-run
individual scenes by calling slate() then the scene block.
"""
from lesson_header import *
import time

myRobot = bot(base_speed=300)
myRobot.voice.select("ryan")
myRobot.voice.set_volume(90)

def slate():
    """Clapper-board reset between scenes."""
    myRobot.move.stop()
    myRobot.camera.center()
    myRobot.anim.stop_blinking()
    myRobot.eyes.color(255, 255, 255)
    myRobot.buzzer.beep(freq=2000, duration_s=0.15)
    time.sleep(0.3)
    myRobot.eyes.color(0, 255, 200)
    time.sleep(2.0)

# ── SCENE 1 — LINE FLUB ──────────────────────────────────────────────────────
print("Scene 1 — Line Flub")
slate()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=2.0, blank_s=0.2)
myRobot.camera.wiggle(cycles=2, amplitude=180)
time.sleep(2.5)
myRobot.eyes.color(255, 255, 0)
myRobot.camera.wiggle(cycles=4, amplitude=220)
myRobot.move.left(seconds=0.2, speed=200)
myRobot.move.right(seconds=0.2, speed=200)
myRobot.buzzer.beep(freq=800, duration_s=0.1)
myRobot.buzzer.beep(freq=900, duration_s=0.1)
myRobot.buzzer.beep(freq=800, duration_s=0.1)
myRobot.anim.stop_blinking()
myRobot.eyes.color(0, 255, 200)
myRobot.camera.center()
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
time.sleep(0.5)

# ── SCENE 2 — EARLY DRIFT ────────────────────────────────────────────────────
print("Scene 2 — Early Drift")
slate()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=2.0, blank_s=0.2)
time.sleep(1.5)
myRobot.move.forward(seconds=0.12)
myRobot.move.backward(seconds=0.12)
time.sleep(0.4)
myRobot.eyes.color(255, 165, 0)
myRobot.move.forward(seconds=0.12)
myRobot.move.backward(seconds=0.12)
myRobot.voice.say("I thought it was drift time!", block=True)
myRobot.anim.stop_blinking()
myRobot.eyes.color(255, 165, 0)
myRobot.move.drift_right(seconds=1.0, speed=320, turn_blend=0.5)
myRobot.move.drift_left(seconds=1.0, speed=320, turn_blend=0.5)
myRobot.move.stop()
myRobot.camera.wiggle(cycles=2, amplitude=150)
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
time.sleep(0.5)

# ── SCENE 3 — SNORING ────────────────────────────────────────────────────────
print("Scene 3 — Snoring")
slate()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.4)
time.sleep(2.0)
myRobot.anim.stop_blinking()
myRobot.eyes.color(0, 30, 60)
myRobot.camera.down(amplitude=300)
time.sleep(0.5)
myRobot.camera.down(amplitude=450)
myRobot.buzzer.beep(freq=280, duration_s=0.7)
time.sleep(0.3)
myRobot.buzzer.beep(freq=240, duration_s=0.9)
time.sleep(0.4)
myRobot.buzzer.beep(freq=280, duration_s=0.7)
time.sleep(0.3)
myRobot.eyes.color(255, 255, 0)
myRobot.camera.center()
myRobot.move.forward(seconds=0.12)
myRobot.move.backward(seconds=0.12)
myRobot.camera.wiggle(cycles=4, amplitude=220)
myRobot.anim.start_blinking(every_s=0.6, blank_s=0.15)
time.sleep(1.5)
myRobot.anim.stop_blinking()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
time.sleep(0.5)

# ── SCENE 4 — HYPNO EYES ─────────────────────────────────────────────────────
print("Scene 4 — Hypno Eyes")
slate()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=2.0, blank_s=0.2)
time.sleep(1.0)
colours = [
    (255,0,0),(0,0,255),(128,0,128),
    (255,165,0),(255,255,0),(0,255,0),
    (255,0,255),(0,255,255),(255,0,0),
    (0,0,255),(128,0,128),(255,0,255),
]
for colour in colours:
    myRobot.eyes.color(*colour)
    time.sleep(0.12)
for f in [400, 600, 900, 1200, 1600, 2000]:
    myRobot.buzzer.beep(freq=f, duration_s=0.12)
time.sleep(0.5)
myRobot.anim.stop_blinking()
myRobot.eyes.color(0, 255, 200)
myRobot.camera.wiggle(cycles=1, amplitude=100)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
time.sleep(0.5)

# ── SCENE 5 — TOO BRIGHT ─────────────────────────────────────────────────────
print("Scene 5 — Too Bright")
slate()
myRobot.eyes.color(0, 255, 200)
time.sleep(1.0)
for _ in range(6):
    myRobot.eyes.color(255, 255, 255)
    myRobot.buzzer.beep(freq=2800, duration_s=0.07)
    time.sleep(0.08)
    myRobot.eyes.off()
    time.sleep(0.08)
myRobot.eyes.color(0, 255, 200)
time.sleep(0.8)
myRobot.voice.say("Who, me?", block=True)
myRobot.camera.wiggle(cycles=2, amplitude=120)
myRobot.anim.stop_blinking()
myRobot.eyes.color(0, 255, 200)
myRobot.camera.center()
time.sleep(2.0)

# ── SCENE 6 — BALL DISTRACTION ───────────────────────────────────────────────
# vision.find_color returns a dict {"objects": [...], "color": ...}
# Check result["objects"] — not result.found
print("Scene 6 — Ball Distraction")
slate()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=2.5, blank_s=0.25)
myRobot.camera.nod(depth=150)
time.sleep(0.8)
myRobot.camera.nod(depth=150)
time.sleep(0.8)
result = myRobot.vision.find_color("red", show=False)
if result["objects"]:
    myRobot.anim.stop_blinking()
    myRobot.eyes.color(0, 255, 0)
    myRobot.camera.center()
    time.sleep(0.2)
    myRobot.move.forward(seconds=1.5, speed=250)
    myRobot.move.left(seconds=0.4, speed=200)
    myRobot.move.forward(seconds=0.8, speed=200)
    myRobot.camera.nod(depth=300)
    time.sleep(0.4)
    myRobot.move.forward(seconds=0.3, speed=150)
    myRobot.camera.nod(depth=300)
    time.sleep(1.0)
    myRobot.move.backward(seconds=2.0, speed=200)
    myRobot.eyes.color(0, 255, 200)
    myRobot.camera.wiggle(cycles=1, amplitude=100)
    myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
else:
    # No ball — chase anyway for the gag
    myRobot.anim.stop_blinking()
    myRobot.eyes.color(0, 255, 0)
    myRobot.move.forward(seconds=1.5, speed=250)
    myRobot.move.left(seconds=0.4, speed=200)
    myRobot.move.forward(seconds=0.8, speed=200)
    myRobot.camera.nod(depth=300)
    time.sleep(0.4)
    myRobot.move.forward(seconds=0.3, speed=150)
    myRobot.camera.nod(depth=300)
    time.sleep(1.5)
    myRobot.move.backward(seconds=2.0, speed=200)
    myRobot.eyes.color(0, 255, 200)
    myRobot.camera.wiggle(cycles=1, amplitude=100)
    myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
time.sleep(0.5)

# ── SCENE 7 — TALKING OVER EACH OTHER ───────────────────────────────────────
print("Scene 7 — Talking Over Each Other")
slate()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=2.0, blank_s=0.2)
myRobot.voice.say("And I am Tur—", block=True)
myRobot.anim.stop_blinking()
myRobot.eyes.color(255, 165, 0)
myRobot.camera.glance_left(amplitude=200, hold_s=0.5)
time.sleep(0.8)
myRobot.voice.say("And I am—", block=True)
myRobot.eyes.color(255, 165, 0)
time.sleep(0.5)
time.sleep(0.8)
myRobot.eyes.color(0, 255, 200)
myRobot.voice.say("And I am Turbo!", block=True)
myRobot.camera.wiggle(cycles=2, amplitude=180)
time.sleep(0.3)
myRobot.voice.say("And I—", block=True)
myRobot.eyes.color(255, 0, 0)
myRobot.camera.shake(width=200)
time.sleep(0.5)

# ── WRAP ─────────────────────────────────────────────────────────────────────
myRobot.move.stop()
myRobot.eyes.off()
myRobot.camera.center()
print("Robot 2 outtakes done.")
