"""
ROBOT 1 — AMY (Toni) — OUTTAKES
Run this on Robot 1. Each scene is self-contained — you can re-run
individual scenes by calling slate() then the scene block.
"""
from lesson_header import *
import time

myRobot = bot(base_speed=300)
myRobot.voice.select("amy")
myRobot.voice.set_volume(90)

def slate():
    """Clapper-board reset between scenes."""
    myRobot.move.stop()
    myRobot.camera.center()
    myRobot.anim.stop_blinking()
    myRobot.eyes.color(255, 255, 255)
    myRobot.buzzer.beep(freq=2000, duration_s=0.15)
    time.sleep(0.3)
    myRobot.eyes.color(0, 255, 200)
    time.sleep(2.0)

# ── SCENE 1 — LINE FLUB ──────────────────────────────────────────────────────
print("Scene 1 — Line Flub")
slate()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
myRobot.camera.nod(depth=150)
myRobot.voice.say("Keeya ora. I am... I am...", block=True)
myRobot.camera.glance_left(amplitude=200, hold_s=0.5)
myRobot.camera.glance_right(amplitude=200, hold_s=0.5)
myRobot.camera.center()
time.sleep(1.5)
myRobot.eyes.color(0, 100, 255)
myRobot.camera.shake(width=150)
myRobot.voice.say("Not. A. Word.", block=True)
time.sleep(0.5)

# ── SCENE 2 — RYAN DRIFTS EARLY ─────────────────────────────────────────────
print("Scene 2 — Ryan Drifts Early")
slate()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
myRobot.voice.say("Welcome to the Paw-neh-keh AI Robot League, where students can—", block=True)
myRobot.camera.glance_right(amplitude=250, hold_s=0.4)
myRobot.anim.stop_blinking()
myRobot.eyes.color(0, 100, 255)
myRobot.voice.say("Not now.", block=True)
myRobot.camera.glance_right(amplitude=300, hold_s=0.5)
time.sleep(2.0)
myRobot.camera.center()
myRobot.eyes.color(0, 255, 200)
myRobot.camera.shake(width=150)
myRobot.voice.say("Every single time.", block=True)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
time.sleep(0.5)

# ── SCENE 3 — RYAN SNORING ───────────────────────────────────────────────────
print("Scene 3 — Ryan Snoring")
slate()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
myRobot.voice.say("Our robots can move, recognise objects, and detect col—", block=True)
myRobot.camera.glance_right(amplitude=250, hold_s=0.8)
time.sleep(1.0)
myRobot.voice.say("Are you snoring?", block=True)
time.sleep(0.8)
myRobot.camera.center()
myRobot.camera.shake(width=150)
myRobot.voice.say("Unbelievable.", block=True)
time.sleep(0.5)

# ── SCENE 4 — HYPNO EYES ─────────────────────────────────────────────────────
print("Scene 4 — Hypno Eyes")
slate()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
myRobot.voice.say("No experience needed, all students are welc—", block=True)
myRobot.camera.glance_right(amplitude=250, hold_s=0.3)
myRobot.anim.stop_blinking()
myRobot.eyes.color(255, 165, 0)
myRobot.voice.say("Not the hypno eyes!", block=True)
myRobot.camera.left(amplitude=350)
time.sleep(1.5)
myRobot.camera.glance_right(amplitude=200, hold_s=0.5)
myRobot.camera.center()
myRobot.eyes.color(0, 255, 200)
myRobot.voice.say("Thank you.", block=True)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
time.sleep(0.5)

# ── SCENE 5 — TOO BRIGHT ─────────────────────────────────────────────────────
print("Scene 5 — Too Bright")
slate()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
myRobot.voice.say("Join us and discover what you can build with—", block=True)
myRobot.camera.glance_right(amplitude=250, hold_s=0.3)
myRobot.anim.stop_blinking()
myRobot.eyes.color(0, 50, 100)
myRobot.move.backward(seconds=0.3, speed=150)
myRobot.voice.say("Too bright.", block=True)
time.sleep(1.0)
myRobot.camera.center()
myRobot.eyes.color(0, 255, 200)
myRobot.camera.shake(width=150)
myRobot.voice.say("Yes. You.", block=True)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
time.sleep(1.5)

# ── SCENE 6 — BALL DISTRACTION ───────────────────────────────────────────────
print("Scene 6 — Ball Distraction")
slate()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
myRobot.voice.say("Our robots can recognise objects and respond to what they see in real time,", block=True)
myRobot.voice.say("which means students can build programmes that—", block=True)
time.sleep(0.8)
myRobot.camera.glance_right(amplitude=300, hold_s=1.0)
myRobot.voice.say("Turbo.", block=True)
time.sleep(1.5)
myRobot.camera.glance_right(amplitude=300, hold_s=0.5)
myRobot.voice.say("Turbo.", block=True)
time.sleep(2.0)
myRobot.camera.center()
myRobot.camera.shake(width=150)
myRobot.voice.say("It saw a ball.", block=True)
time.sleep(0.5)

# ── SCENE 7 — TALKING OVER EACH OTHER ───────────────────────────────────────
print("Scene 7 — Talking Over Each Other")
slate()
myRobot.eyes.color(0, 255, 200)
myRobot.anim.start_blinking(every_s=3.0, blank_s=0.3)
myRobot.voice.say("Keeya ora I am—", block=True)
myRobot.anim.stop_blinking()
myRobot.eyes.color(0, 100, 255)
myRobot.camera.glance_right(amplitude=200, hold_s=0.5)
time.sleep(0.8)
myRobot.voice.say("Keeya ora I—", block=True)
myRobot.eyes.color(255, 165, 0)
time.sleep(0.5)
myRobot.voice.say("You go.", block=True)
time.sleep(1.0)
myRobot.voice.say("Keeya ora I am—", block=True)
myRobot.anim.stop_blinking()
myRobot.eyes.color(0, 50, 150)
myRobot.camera.shake(width=200)
myRobot.voice.say("Start again.", block=True)
time.sleep(0.5)

# ── WRAP ─────────────────────────────────────────────────────────────────────
myRobot.move.stop()
myRobot.eyes.off()
myRobot.camera.center()
print("Robot 1 outtakes done.")
